ibm_cloud_fail_over/__init__.py,sha256=WNrxDTz--FWGcrVobE9iwSYQndBvY9XULngT93fguXg,339
ibm_cloud_fail_over/ibm_cloud_fail_over.py,sha256=ncIllmqNanLzORjTCJulLR86itLFNry7LEC7QWF90rI,29771
ibm_cloud_fail_over-1.0.15.dist-info/METADATA,sha256=NxIb6NXTjS75uMrgTtsmQszkmBsLcA4N-1pQ59PBGxU,7105
ibm_cloud_fail_over-1.0.15.dist-info/WHEEL,sha256=qtCwoSJWgHk21S1Kb4ihdzI2rlJ1ZKaIurTj_ngOhyQ,87
ibm_cloud_fail_over-1.0.15.dist-info/licenses/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
ibm_cloud_fail_over-1.0.15.dist-info/RECORD,,
